const assert=require('node:assert/strict');
const core=require('../app/src/main/assets/core.js');
const s=core.initial();
assert.equal(core.money('12,50'),1250);assert.equal(core.money('12.50'),1250);assert.ok(Number.isNaN(core.money('-5')));
assert.ok(Number.isNaN(core.money('1.234')));
s.customers.push({id:'c1',name:'Ana',phone:'70000000'});
s.products.push({id:'p1',name:'Biblia',price:2500,stock:5});
assert.equal(core.calculate([{productId:'p1',qty:2}],s.products),5000);
const q=core.createOrder(s,'quote','c1',[{productId:'p1',qty:2}]);
assert.equal(s.products[0].stock,5);
const sale=core.convertQuote(s,q.id);assert.equal(s.products[0].stock,3);assert.equal(sale.total,5000);
assert.throws(()=>core.convertQuote(s,q.id),/Ya fue convertida/);
assert.throws(()=>core.createOrder(s,'sale','c1',[{productId:'p1',qty:4}]),/Inventario insuficiente/);
assert.equal(s.products[0].stock,3);
assert.equal(core.totals(s).pending,5000);
assert.ok(core.message(sale,s.settings).includes('no constituye factura fiscal'));
assert.throws(()=>core.restore({version:2}),/incompatible/);
assert.equal(core.restore(JSON.parse(JSON.stringify(s))).sales.length,1);
assert.equal(core.esc('<script>'),'&lt;script&gt;');
console.log('OK: 15 verificaciones de cálculo, stock, cotizaciones, ventas, importación y seguridad');
