import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { achievements, advanceSession, aidCosts, answerQuestion, currentQuestion, dateKey, duelWinner, freshSave, heroes, questions, restoreSave, secondDuelTurn, settleSession, stars, startDuel, startSession, tickSession, toggleFavorite, unlocked, useAid } from '../src/game.ts';
import { ProgressStore } from '../src/store.ts';

fs.mkdirSync('entregables', { recursive: true });
const checks = [];
function check(name, callback) { callback(); checks.push(name); }
function finish(save, correct = 12) {
  for (let index = 0; index < 12; index++) {
    answerQuestion(save, index < correct ? currentQuestion(save).answer : 1);
    advanceSession(save);
  }
  return save.session;
}
const normalized = value => value.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]/g, '');
check('240 preguntas propias, cuatro opciones únicas y pasajes con evidencia', () => {
  assert.equal(heroes.length, 12);
  assert.equal(questions.length, 240);
  assert.equal(new Set(questions.map(item => item.id)).size, 240);
  assert.equal(new Set(questions.map(item => item.prompt)).size, 240);
  for (const item of heroes) assert.equal(questions.filter(question => question.heroId === item.id).length, 20);
  for (const question of questions) {
    assert.equal(question.choices.length, 4);
    assert.equal(new Set(question.choices.map(normalized)).size, 4);
    assert.ok(question.answer >= 0 && question.answer < 4);
    assert.ok(question.reference.length > 5 && question.verseKeys.length > 0 && question.explanation.length > 25);
    for (const term of question.evidence) assert.ok(normalized(question.verse).includes(normalized(term)), question.id + ': ' + term);
  }
  const report = JSON.parse(fs.readFileSync('docs/fuentes-preguntas.json'));
  assert.equal(report.questionsSHA256, crypto.createHash('sha256').update(fs.readFileSync('src/data/questions.json')).digest('hex'));
});
check('Logo original intacto, doce retratos y nuevo ícono de 512 px', () => {
  assert.equal(crypto.createHash('sha256').update(fs.readFileSync('public/brand/scala-original.png')).digest('hex'), 'a6ada3a8a2afe73f0a38718fefd55b9734984800872049f5cd56f2259cec85e1');
  for (const item of heroes) assert.ok(fs.statSync('public/heroes/' + item.id + '.webp').size > 10000);
  const png = fs.readFileSync('public/brand/heroes-icon.png');
  assert.equal(png.readUInt32BE(16), 512);
  assert.equal(png.readUInt32BE(20), 512);
  assert.deepEqual(png, fs.readFileSync('android/app/src/main/res/mipmap-nodpi/scala_launcher_art.png'));
});
check('Desbloqueo por experiencia y rondas con opciones mezcladas', () => {
  const save = freshSave();
  assert.equal(save.coins, 120);
  assert.ok(unlocked(save, 'noe'));
  assert.equal(startSession(save, 'journey', 'abraham', 1), null);
  assert.equal(unlocked(save, 'abraham'), false);
  save.xp = 100;
  assert.ok(unlocked(save, 'abraham'));
  const session = startSession(save, 'journey', 'abraham', 42);
  assert.equal(new Set(session.questionIds).size, 12);
  for (const order of session.choiceOrders) assert.deepEqual([...order].sort(), [0, 1, 2, 3]);
  assert.ok(new Set(session.choiceOrders.map(order => order.indexOf(0))).size > 1);
});
check('Desafío diario reproducible con los doce personajes', () => {
  const one = freshSave();
  const two = freshSave();
  const a = startSession(one, 'daily', 'noe', 10, '2026-10-09');
  const b = startSession(two, 'daily', 'noe', 20, '2026-10-09');
  assert.deepEqual(a.questionIds, b.questionIds);
  assert.equal(new Set(a.questionIds.map(id => questions.find(item => item.id === id).heroId)).size, 12);
  const c = startSession(two, 'daily', 'noe', 20, '2026-10-10');
  assert.notDeepEqual(c.questionIds, a.questionIds);
  assert.match(dateKey(), /^\d{4}-\d{2}-\d{2}$/);
});
check('Un doble toque no duplica respuestas ni penalizaciones', () => {
  const save = freshSave();
  startSession(save, 'journey', 'noe', 7);
  assert.equal(advanceSession(save), 'blocked');
  assert.equal(answerQuestion(save, -1), null);
  assert.equal(answerQuestion(save, 4), null);
  assert.equal(answerQuestion(save, 1).correct, false);
  assert.equal(answerQuestion(save, 0), null);
  assert.equal(save.session.penaltyMs, 5000);
  tickSession(save, 1000);
  assert.equal(save.session.elapsedMs, 0);
});
check('Ayudas atómicas, dos opciones incorrectas y reloj congelado', () => {
  const save = freshSave();
  startSession(save, 'journey', 'noe', 13);
  assert.deepEqual(aidCosts, { half: 25, verse: 20, pause: 30 });
  assert.ok(useAid(save, 'half').applied);
  assert.equal(save.coins, 95);
  assert.equal(save.session.removedChoices.length, 2);
  assert.ok(!save.session.removedChoices.includes(currentQuestion(save).answer));
  assert.equal(useAid(save, 'half').applied, false);
  assert.equal(answerQuestion(save, save.session.removedChoices[0]), null);
  assert.ok(useAid(save, 'verse').applied);
  assert.equal(save.coins, 75);
  assert.ok(useAid(save, 'pause').applied);
  assert.equal(save.coins, 45);
  for (let index = 0; index < 6; index++) tickSession(save, 2000);
  assert.equal(save.session.elapsedMs, 0);
  assert.equal(save.session.frozenMsLeft, 0);
  tickSession(save, 1000);
  assert.equal(save.session.elapsedMs, 1000);
  assert.equal(useAid(save, 'pause').applied, false);
  const resumed = restoreSave(JSON.parse(JSON.stringify(save)));
  assert.deepEqual(resumed.session.removedChoices, save.session.removedChoices);
  assert.equal(resumed.session.halfUsed, true);
  assert.equal(resumed.session.verseUsed, true);
  assert.equal(resumed.coins, 45);
  answerQuestion(resumed, 0);
  advanceSession(resumed);
  assert.equal(resumed.session.halfUsed, false);
  assert.equal(resumed.session.verseUsed, false);
  assert.equal(resumed.session.freezeUsed, true);
  resumed.coins = 19;
  assert.equal(useAid(resumed, 'verse').applied, false);
  assert.equal(resumed.coins, 19);
});
check('Recompensas exactas y liquidación idempotente', () => {
  const save = freshSave();
  startSession(save, 'journey', 'noe', 14);
  finish(save);
  assert.equal(save.xp, 220);
  assert.equal(save.coins, 166);
  assert.equal(save.rounds, 1);
  assert.equal(save.heroBest.noe, 12);
  assert.equal(save.mastery.length, 12);
  assert.equal(save.bestStreak, 12);
  assert.equal(stars(12), 3);
  assert.equal(stars(9), 2);
  assert.equal(stars(6), 1);
  assert.equal(stars(5), 0);
  const snapshot = JSON.stringify(save);
  settleSession(save);
  advanceSession(save);
  assert.equal(JSON.stringify(save), snapshot);
  assert.ok(achievements(save).find(item => item.id === 'first').earned);
  assert.ok(achievements(save).find(item => item.id === 'perfect').earned);
});
check('La práctica es gratis, no entrega XP y permite aprender sin reloj', () => {
  const save = freshSave();
  startSession(save, 'practice', 'noe', 20);
  useAid(save, 'half');
  useAid(save, 'verse');
  tickSession(save, 2000);
  assert.equal(save.session.elapsedMs, 0);
  finish(save, 11);
  assert.equal(save.session.penaltyMs, 0);
  assert.equal(save.coins, 120);
  assert.equal(save.xp, 0);
  assert.equal(save.mastery.length, 11);
});
check('El premio diario se entrega una sola vez por fecha', () => {
  const save = freshSave();
  startSession(save, 'daily', 'noe', 30, '2026-10-09');
  finish(save);
  assert.equal(save.xp, 245);
  assert.equal(save.coins, 186);
  startSession(save, 'daily', 'noe', 31, '2026-10-09');
  finish(save);
  assert.equal(save.session.rewardXp, 0);
  assert.equal(save.session.rewardCoins, 0);
  assert.equal(save.xp, 245);
  startSession(save, 'daily', 'noe', 32, '2026-10-10');
  finish(save);
  assert.equal(save.xp, 490);
  assert.deepEqual(save.completedDaily, ['2026-10-09', '2026-10-10']);
});
check('Duelo persistente con igualdad de preguntas, opciones y reglas', () => {
  const save = freshSave();
  assert.ok(startDuel(save, ['Ana', 'Luis'], 'noe', 40));
  const ids = [...save.session.questionIds];
  const orders = [...save.session.choiceOrders];
  assert.equal(useAid(save, 'half').applied, false);
  tickSession(save, 1200);
  finish(save, 10);
  assert.equal(save.duel.stage, 1);
  settleSession(save);
  assert.equal(save.duel.stage, 1);
  const resumed = restoreSave(JSON.parse(JSON.stringify(save)));
  assert.ok(secondDuelTurn(resumed));
  assert.equal(secondDuelTurn(resumed), false);
  assert.deepEqual(resumed.session.questionIds, ids);
  assert.deepEqual(resumed.session.choiceOrders, orders);
  tickSession(resumed, 1500);
  finish(resumed, 11);
  assert.equal(resumed.duel.stage, 2);
  assert.equal(duelWinner(resumed.duel), 1);
  assert.equal(resumed.xp, 0);
  assert.equal(resumed.coins, 120);
  assert.equal(resumed.rounds, 0);
  assert.equal(resumed.history.length, 0);
  assert.equal(secondDuelTurn(resumed), false);
  resumed.duel.results[0].correct = 11;
  resumed.duel.results[0].elapsedMs = resumed.duel.results[1].elapsedMs;
  assert.equal(duelWinner(resumed.duel), -1);
  resumed.duel.results[0].elapsedMs += 1000;
  assert.equal(duelWinner(resumed.duel), 1);
});
check('Restauración defensiva y favoritos sin duplicados', () => {
  const save = freshSave();
  save.settings.sound = false;
  startSession(save, 'journey', 'noe', 50);
  answerQuestion(save, 0);
  const raw = JSON.parse(JSON.stringify(save));
  raw.session.answers[0].correct = false;
  const resumed = restoreSave(raw);
  assert.equal(resumed.session.answers[0].correct, true);
  assert.equal(resumed.settings.sound, false);
  assert.equal(toggleFavorite(resumed, 'missing'), false);
  assert.equal(toggleFavorite(resumed, 'noe-01'), true);
  assert.equal(toggleFavorite(resumed, 'noe-01'), false);
  assert.equal(resumed.favorites.length, 0);
  assert.deepEqual(restoreSave(null), freshSave());
  assert.deepEqual(restoreSave({ schemaVersion: 2 }), freshSave());
  const malformed = restoreSave({ schemaVersion: 1, xp: NaN, coins: -900, mastery: ['fake'], favorites: ['fake'], session: { mode: 'journey', questionIds: ['fake'] } });
  assert.equal(malformed.xp, 0);
  assert.equal(malformed.coins, 0);
  assert.equal(malformed.session, null);
  assert.equal(malformed.mastery.length, 0);
});
const stored = new Map();
globalThis.localStorage = { getItem: key => stored.get(key) ?? null, setItem: (key, value) => stored.set(key, value) };
const storage = new ProgressStore();
const first = freshSave();
const pending = storage.write(first);
first.coins = 111;
await Promise.all([pending, storage.write(first)]);
assert.equal((await storage.read()).save.coins, 111);
for (const key of stored.keys()) stored.set(key, 'broken json');
assert.equal((await storage.read()).recovered, true);
checks.push('Guardado serializado y recuperación de JSON corrupto');
const report = { passed: true, questions: questions.length, heroes: heroes.length, checks };
fs.writeFileSync('entregables/pruebas-motor.json', JSON.stringify(report, null, 2) + '\n');
console.log(JSON.stringify(report));
