camel.main.name=scala-automation-pro
camel.main.profile=prod
camel.main.shutdown-timeout=30
camel.main.shutdown-suppress-logging-on-timeout=false

camel.component.amqp.host=artemis
camel.component.amqp.port=5672
camel.component.amqp.username={{env:ARTEMIS_USER}}
camel.component.amqp.password={{env:ARTEMIS_PASSWORD}}
camel.component.amqp.test-connection-on-startup=true
camel.component.amqp.cache-level-name=CACHE_CONSUMER
